# Generated by Django 3.1.3 on 2021-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_netisp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
