# Generated by Django 3.1.3 on 2021-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0005_customer_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
