# Generated by Django 3.1.3 on 2021-02-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_netisp", "0008_address_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
