# Generated by Django 3.1.3 on 2021-02-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0010_billingpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('primary_applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
