# Generated by Django 3.1.3 on 2021-02-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0122_standardize_name_length"),
        ("netbox_netisp", "0012_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="device_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="dcim.devicetype",
            ),
            preserve_default=False,
        ),
    ]
