# Generated by Django 3.1.3 on 2021-02-28 00:55

from django.db import migrations
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0014_customerpremiseequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpremiseequipment',
            name='ip_address',
            field=ipam.fields.IPAddressField(),
        ),
    ]
