# Generated by Django 3.1.3 on 2021-02-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0016_antennaprofile_radioaccesspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennaprofile',
            name='name',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
    ]
