# Generated by Django 3.1.3 on 2021-03-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_netisp', '0017_antennaprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.address')),
                ('billing_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.billingpackage')),
                ('cpe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.customerpremiseequipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WirelessService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_netisp.service')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.radioaccesspoint')),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_netisp.service',),
        ),
        migrations.CreateModel(
            name='FiberService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_netisp.service')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.interface')),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_netisp.service',),
        ),
    ]
