# Generated by Django 3.1.3 on 2021-03-15 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netbox_netisp', '0019_radioaccesspoint_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_opened', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
                ('priority', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('hire_date', models.DateTimeField()),
                ('permission_level', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
