# Generated by Django 3.1.3 on 2021-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0021_auto_20210315_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(default='Upgrade', max_length=255),
            preserve_default=False,
        ),
    ]
