# Generated by Django 3.1.3 on 2021-03-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0022_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Actige\x7f\x7fve', max_length=255),
            preserve_default=False,
        ),
    ]
