# Generated by Django 3.1.3 on 2021-03-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0023_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
