# Generated by Django 3.1.7 on 2021-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0024_auto_20210317_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennaprofile',
            name='azimuth',
            field=models.IntegerField(max_length=30),
        ),
    ]
