# Generated by Django 3.1.7 on 2021-03-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0025_auto_20210326_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennaprofile',
            name='azimuth',
            field=models.IntegerField(),
        ),
    ]
