# Generated by Django 3.1.7 on 2021-03-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0026_auto_20210326_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cpe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.customerpremiseequipment'),
        ),
    ]
