# Generated by Django 3.1.7 on 2021-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0027_auto_20210326_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Active', max_length=30),
            preserve_default=False,
        ),
    ]
