# Generated by Django 3.1.7 on 2021-03-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_netisp', '0028_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_netisp.ticket')),
                ('rssi', models.IntegerField()),
                ('local_noise_floor', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_netisp.ticket',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='technician',
            field=models.CharField(default='Schylar', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WirelessInstallTicket',
            fields=[
                ('wirelessticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_netisp.wirelessticket')),
                ('survey_height', models.IntegerField()),
                ('conclusion', models.CharField(max_length=255)),
                ('cpe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.device')),
            ],
            options={
                'abstract': False,
            },
            bases=('netbox_netisp.wirelessticket',),
        ),
    ]
