# Generated by Django 3.1.7 on 2021-03-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0029_auto_20210328_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelessinstallticket',
            name='conclusion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wirelessinstallticket',
            name='survey_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wirelessticket',
            name='local_noise_floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wirelessticket',
            name='rssi',
            field=models.IntegerField(null=True),
        ),
    ]
