# Generated by Django 3.1.7 on 2021-03-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0030_auto_20210328_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WirelessInstallTicket',
        ),
    ]
