# Generated by Django 3.1.7 on 2021-03-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_netisp', '0031_delete_wirelessinstallticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelessticket',
            name='conclusion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wirelessticket',
            name='cpe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.device'),
        ),
        migrations.AddField(
            model_name='wirelessticket',
            name='survey_height',
            field=models.IntegerField(null=True),
        ),
    ]
