# Generated by Django 3.2 on 2021-04-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0033_auto_20210422_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttachment',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.account')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.address')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
