# Generated by Django 3.2 on 2021-04-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netisp', '0035_rename_accountattachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.account'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.address'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_netisp.service'),
        ),
    ]
