# Generated by Django 3.2 on 2021-04-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0130_sitegroup'),
        ('netbox_netisp', '0038_gponsplitter_ispactivedevice_olt_ont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gponsplitter',
            name='created',
        ),
        migrations.RemoveField(
            model_name='gponsplitter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gponsplitter',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='gponsplitter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='ispactivedevice',
            name='uuid',
        ),
        migrations.CreateModel(
            name='ISPDevice',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=255)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.devicetype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.manufacturer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gponsplitter',
            name='ispdevice_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_netisp.ispdevice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ispactivedevice',
            name='ispdevice_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_netisp.ispdevice'),
            preserve_default=False,
        ),
    ]
